manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rampadc
      url-base: https://github.com/rampadc
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: rampadc
      revision: 7ab7846a95b233c3ada0e0605b972f36353e7bc4
  self:
    path: config
