import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'engineering/architecture'}],
    },
    {
      type: 'category',
      label: 'SPEC',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'engineering/spec'}],
    },
    {type: 'category', label: 'Reference', items: [{type: 'autogenerated', dirName: 'reference'}]},
  ],
};

export default sidebars;
